### ISSUE TITLE
Datetime conversion bug

### ISSUE THREAD

**Issue by jennet** [DataDock/datadock#147]
We might be missing an implementation of `datetime`

> [2019-03-01 17:47:40Z] - ERROR - CSV conversion failed. Invalid CSV table metadata: Unable to match the datatype 'datetime' to a known datatype

I have [successfully uploaded the dataset](https://datadock.io/datadockdemo/police/page/resource/201812MetropolitanStopAndSearchcsv/row_8.html) using `date` 

(I also noticed a typo, see #145, which if datetime is not needing would become unneccesary to fix obviously)

**Comment by kal** [comment]
@jennet - I just tried it out with the same CSV file. I left the column as Date & Time (which the datatype sniffer had selected), and it processed correctly. I did update the CSVWeb processor yesterday, and that update included better handling for date and date/time values, so I think that is why I can't reproduce the bug.

Can you try again and check, if it works for you too then I think we can close this one.

**Comment by jennet** [comment]
Yep confirmed the `datetime` conversion is working as expected now.
