### ISSUE TITLE
API search for portal buttons does not return results

### ISSUE THREAD

**Issue by kal** [DataDock/datadock#157]
When you click on the user-defined buttons in the portal, you get no results even though there are some datasets tagged with the tag specified in the button. 

See https://datadock.io/kal/more_data/page/index.html - expect clicking on "Heritage" to filter the list of datasets down to two, but got no results (both of the datasets are shown on the site).

There is probably a broader issue here - the buttons use the search API, which will only search against datasets that have been indexed in our database. However, the portal page will show *all* the datasets for that user/org portal (including ones that are "hidden from search"). So perhaps the functionality here should be pure JS, just filtering the list of datasets when you click on a button.

**Comment by kal** [comment]
I changed the portal page buttons to use buttons rather than cards because it allows me to more clearly show an active selection. When you select a button now, rather than do a search API call, it just filters the dataset cards to show only the ones with that tag.

@jennet - you can see the changes I made at https://staging.datadock.io/kal/data_dev/page/index.html

**Comment by jennet** [comment]
@kal do you think the breadcrumb is a clear enough way to "clear search" (i.e. reset the page).
I wonder if perhaps we should open an issue to add a button to clear any filtering.

**Comment by kal** [comment]
@jennet - you can click on an active button to clear the filter

**Comment by jennet** [comment]
ah!
