### ISSUE TITLE
datatype sniffer treats empty columns as booleans

### ISSUE THREAD

**Issue by jennet** [DataDock/datadock#181]

**Comment by jennet** [comment]
Kal added this in commit 0a28e4f01dd33a5e970d57dd136b49477ded36aa

**Comment by kal** [comment]
What is happening here is that the datatype sniffer can't choose a datatype so it returns all of them, and then the metadata editor picks the first one. The datatype sniffer does also return a flag that says that all of the values were empty, so the metadata editor should check that. If a column is completely empty it also makes sense to suppress it from output.

**Comment by kal** [comment]
Fixed by #11fb8f6
