### ISSUE TITLE
Error on signing up.

### ISSUE THREAD

**Issue by ryanlio017** [DataDock/datadock#227]
Request ID: |900e9fb6-4fd309b541afbcd5.
Error on signing up.
Please advice.

**Comment by kal** [comment]
Thanks for letting me know! There was a database outage that caused sign-up and sign-in both to fail. That is now fixed and you should be able to retry your sign-up. As the database was down, my guess is that your account won't exist yet and you will have to go through the OAuth sign-up procedure again. If you hit any problems please let us know!
