### ISSUE TITLE
Additional logging around ntriples attachments to github release

### ISSUE THREAD

**Issue by jennet** [DataDock/datadock#66]
Job failed to attach the gzipped ntriples file to the release in GitHub. Unfortunately there is no further detail in the logs about why that happened. We probably need to start with adding more logging in that bit of the code if the attachment fails.

In any case, if the job does fail at this point we should really bubble up the error and make sure we don't treat the dataset as successfully created.

**Comment by kal** [comment]
I looks like this has already been addressed in the code. The code that zips the ntriples and attaches it to the release is warpped in try/catch and will throw a WorkerException if it fails. WorkerExceptions are then caught at a higher level and turned into error messages on the job.
