### ISSUE TITLE
Top level navigation is not intuitive on the Add Data page

### ISSUE THREAD

**Issue by kal** [DataDock/datadock#86]
Clicking on the Choose, Define and Upload buttons doesn't do anything, because they look clickable I would expect them to allow me to quickly skip backwards and forwards through those three main steps.

I think either they should be clickable and work, or they shouldn't be clickable and so shouldn't have any mouse-over effects that make them seem like they are some sort of active control.

**Comment by jennet** [comment]
This is a bug, the choose step should be clickable and restart you (but the other two steps are not clickable and this would have to be added as an enhancement if we decide that it's necessary)
