### ISSUE TITLE
Cannot publish to an organisation repository

### ISSUE THREAD

**Issue by kal** [DataDock/datadock#87]
I cannot publish data to an organisation repository under the NetworkedPlanet org. I have write (and admin) access to this repository but when I attempt to upload data to the repository I get the following error message:

Publish data API has reported an error: "Repository does not exist or you do not have the required authorization to publish to it."

**Comment by jennet** [comment]
I have just tried to upload to an org of mine and it's [uploaded fine](http://jenwilliams.me.uk/datadock/page/dataset/riverLevels.html).

However I am getting an error on the portal root page, so I'll open an issue for that separately.

Can you try again with a different org, or another repo in that org?

**Comment by kal** [comment]
I can publish data to the datadocktestorg, but not to the NetworkedPlanet org. I have granted the community server access to the NetworkedPlanet org and then I tried logging in an out and I even tried doing a full delete of my DD account to try and force a reset of permissions but none of that has worked.

**Comment by kal** [comment]
I just noticed that the org name gets forced to lower case when you go to Add Data. It starts off as NetworkedPlanet, but as soon as I get to the Add Data page it becomes networkedplanet everywhere. I wonder if that is the problem - though I had thought that org names were not case sensitive.

**Comment by kal** [comment]
Yep, looks like that was the cause. Traced it to some code that I had added when we changed around the routing, it was forcing the URL to lower case and removing that makes the import work fine.

**Comment by kal** [comment]
@jennet - the issue you mentioned about an error on the portal root page is it the same as #90?
