### ISSUE TITLE
File size limit on community server

### ISSUE THREAD

**Issue by jennet** [DataDock/datadock#88]
We need to double check the file size limits on the new server to make sure it has not been reduced (I think it has). I get this error when hitting the "Publish" button on a 1.3MB file:

**Comment by jennet** [comment]
<img width="1155" alt="screenshot 2018-12-14 at 17 34 31" src="https://user-images.githubusercontent.com/4940135/50018339-e4adc100-ffc6-11e8-963c-f7abd6c914fa.png">

**Comment by kal** [comment]
I updated the nginx configuration on the server (for community and for what will become live) to allow up to 20M to go through the nginx proxy. ASP.NET has a default 28M limit for file uploads so the nginx limit will kick in first, but I think for now 20M is probably high enough
