### ISSUE TITLE
Allow deletion of a dataset from the repository

### ISSUE THREAD

**Issue by kal** [DataDock/datadock#93]
Currently deleting a dataset only deletes the DD index of the dataset, it does not actually remove any files from the user's repository. We should add support for creating a job that deletes a dataset from a repository, removing the RDF, HTML, CSV and quince files for that dataset.

**Comment by kal** [comment]
There is already code in the worker to do this, so we might only need to change the code at the web front-end so that it actually kicks off a delete job rather than just deleting the metadata.

**Comment by kal** [comment]
Keep the current UI, but make sure that it tells the user that it will delete all the data from GitHub on the confirmation page.

**Comment by jennet** [comment]
Current delete page info:
![delete](https://user-images.githubusercontent.com/4940135/52866094-dfd7cb80-3135-11e9-8136-3b6398bfe7aa.PNG)
